apiVersion: v1
kind: ServiceAccount
metadata:
  name: mxpc-cli-installer-sa
  namespace: mendix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mxpc-cli-installer-cluster-role
  namespace: mendix
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mxpc-cli-installer-cluster-rolebinding
  namespace: mendix 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mxpc-cli-installer-cluster-role
subjects:
- namespace: mendix 
  kind: ServiceAccount
  name: mxpc-cli-installer-sa