clusterID: "${cluster_id}"
clusterSecret: "${cluster_secret}"
mendix_operator_version: "${mendix_operator_version}"
AWSRegion: "${awsregion}"
registry:
      pullUrl: "${registry_pullurl}"
      pushUrl: "${registry_pushurl}"
      repositoryName: "${registry_repository}"
      iamRole: "${registry_iam_role}"
storageplan:
    file:
        name: "${storageplan_file_name}"
        endPoint: "${storageplan_file_regional_endpoint}"
        accessKey: "${storageplan_file_accesskey}"
        secretKey: "${storageplan_file_secretkey}"
    database:
        name: "${storageplan_database_name}"
        host: "${storageplan_database_host}"
        port: "${storageplan_database_port}"
        databaseName: "${storageplan_database_dbname}"
        username: "${storageplan_database_admin_username}"
        password: "${storageplan_database_admin_password}"
ingress:
    className: "nginx"
    domainName: "${ingress_domainname}"