apiVersion: v1
kind: Secret
metadata:
  name: mendix-installer-config-file
  namespace: mendix
type: Opaque
stringData:
  mendix-installer-config-file: |
    namespace: mendix
    cluster_mode: connected
    mask:
      database_plan: false
      storage_plan: false
      ingress: true
      registry: true
      proxy: false
      custom_tls: false
    ingress:
      type: kubernetes-ingress
      enable_tls: true
      k8s_ingress:
        domain: "{{ .Values.ingress.domainName }}"
        useCustomIngressClass: true
        customIngressClass: nginx
        customIngressClassAsAnnotation: true
        path: /
      service: null
    registry:
      type: amazon-ecr
      ecr_registry:
        name: "{{ .Values.registry.repositoryName }}"
        hostname: "{{ .Values.registry.pullUrl }}"
        aws_region: "{{ .Values.awsRegion }}"
        is_static_credential: false
        aws_iam_role: "{{ .Values.registry.iamRole }}"
        kubernetes_service_account: "mendix-builder"
