promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://loki-stack.loki.svc.cluster.local:3100/loki/api/v1/push

loki:
  persistence:
    enabled: true
    size: 30Gi
  config:
    chunk_store_config:
      max_look_back_period: 60d
    table_manager:
      retention_period: 60d